// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:bf62f0d9-7574-4cd0-93b7-fff59eb6ba02';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = 'f10a34fd37c84d6a8032f5e038bba15d';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'efbffce6-8953-4858-bc9b-e56f6ced5769';
var aws_project_name = 'sundayze-io';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'sundayzeio-mobilehub-947613058';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
